package web

import (
	"embed"
	"io/fs"
)

// Dist is generated by the frontend build and embedded into the server.
//
//go:embed dist/*
var dist embed.FS

func Files() (fs.FS, error) { return fs.Sub(dist, "dist") }
